/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_project;

/**
 *
 * @author Bimindu
 */
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class add_patient extends javax.swing.JFrame {

    /**
     * Creates new form add_patient
     */
    final String password ="";
    final String username="root";
    final String URL = "jdbc:mysql://localhost:3308/hospital";    
    Connection con = null;
    PreparedStatement Insertps = null;
    ResultSet rs =null;
    String WC;
    public add_patient(String wccode) {
        WC = wccode;
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                con = DriverManager.getConnection(URL,username,password);
            } catch (SQLException ex) {
                Logger.getLogger(add_patient.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(add_patient.class.getName()).log(Level.SEVERE, null, ex);
        }
         getcomboboxitems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void getcomboboxitems(){
        String sql = "SELECT DISTINCT DIETCODE from dietfood";
        try {
            Insertps = con.prepareStatement(sql);
           
            rs = Insertps.executeQuery();
            while(rs.next()){
                diet_code.addItem(rs.getString("DIETCODE"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(add_patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        agespinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        p_code = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bed_code = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        disease = new javax.swing.JTextArea();
        allergy = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        editpatientbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();
        removepatientbutton = new javax.swing.JButton();
        addbutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        logoutbutton = new javax.swing.JButton();
        orderfoodbutton = new javax.swing.JButton();
        diet_code = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("NEW PATIENT");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, 296, 61));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 130, -1, -1));

        p_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_nameActionPerformed(evt);
            }
        });
        jPanel1.add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 415, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Age");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 37, -1));

        agespinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 110, 1));
        jPanel1.add(agespinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 415, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Patient Code");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 220, -1, -1));
        jPanel1.add(p_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 415, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Bed Code");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 80, -1));

        bed_code.setText("\n");
        bed_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bed_codeActionPerformed(evt);
            }
        });
        jPanel1.add(bed_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, 415, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Diet Code\n");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 70, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Disease");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, -1, -1));

        disease.setColumns(20);
        disease.setRows(5);
        jScrollPane1.setViewportView(disease);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 415, 90));
        jPanel1.add(allergy, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 450, 420, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Allergies");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, -1, 20));

        editpatientbutton.setBackground(new java.awt.Color(204, 0, 0));
        editpatientbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        editpatientbutton.setForeground(new java.awt.Color(255, 255, 255));
        editpatientbutton.setText("Edit Patient");
        editpatientbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editpatientbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(editpatientbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 370, 80));

        cancelbutton.setBackground(new java.awt.Color(255, 0, 0));
        cancelbutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        cancelbutton.setForeground(new java.awt.Color(242, 242, 242));
        cancelbutton.setText("Clear");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, 210, 50));

        removepatientbutton.setBackground(new java.awt.Color(204, 102, 0));
        removepatientbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        removepatientbutton.setForeground(new java.awt.Color(255, 255, 255));
        removepatientbutton.setText("Remove Patient");
        removepatientbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removepatientbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(removepatientbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 370, 80));

        addbutton.setBackground(new java.awt.Color(0, 153, 0));
        addbutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        addbutton.setForeground(new java.awt.Color(242, 242, 242));
        addbutton.setText("ADD");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1182, 490, 210, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Add Patient");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 370, 80));

        logoutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/4400828_1_70x70.png"))); // NOI18N
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, -1, -1));

        orderfoodbutton.setBackground(new java.awt.Color(153, 0, 153));
        orderfoodbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        orderfoodbutton.setForeground(new java.awt.Color(255, 255, 255));
        orderfoodbutton.setText("Order Food");
        orderfoodbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderfoodbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(orderfoodbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 370, 80));

        diet_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diet_codeActionPerformed(evt);
            }
        });
        jPanel1.add(diet_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 300, 410, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/doctor.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_nameActionPerformed

    private void removepatientbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removepatientbuttonActionPerformed
        // TODO add your handling code here:
        Remove_patient rp =new Remove_patient(WC);
        rp.setVisible(true);
        dispose();
    }//GEN-LAST:event_removepatientbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
        login log =new login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        // TODO add your handling code here:
        p_name.setText("");
        p_code.setText("");
        agespinner.setValue(1);
        bed_code.setText("");
        disease.setText("");
        allergy.setText("");
        
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void orderfoodbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderfoodbuttonActionPerformed
        // TODO add your handling code here:
        order_food of = new order_food(WC);
        of.setVisible(true);
        dispose();
    }//GEN-LAST:event_orderfoodbuttonActionPerformed

    private void editpatientbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editpatientbuttonActionPerformed
        // TODO add your handling code here:
        Edit_patient ep = new Edit_patient(WC);
        ep.setVisible(true);
        dispose();
    }//GEN-LAST:event_editpatientbuttonActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        
        String patient_code = p_code.getText();
        String patient_name = p_name.getText();
        String bed = bed_code.getText();
        String diet = diet_code.getSelectedItem().toString();
        String allergies = allergy.getText();
        if(!patient_name.isEmpty()){
            if(!patient_code.isEmpty()){
                if(!bed.isEmpty()){
                    try {
                        int i;
                        Insertps = con.prepareCall("INSERT INTO patient values(?,?,?,?,?)");
                        Insertps.setString(1, patient_code);
                        Insertps.setString(2, patient_name);
                        Insertps.setString(3, diet);
                        Insertps.setString(4,bed);
                        Insertps.setString(5, allergies);
                        i=Insertps.executeUpdate();
                        if(i==1){
                            JOptionPane.showMessageDialog(null, "Success!!");
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(add_patient.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
            }
        }
        
            
            
    }//GEN-LAST:event_addbuttonActionPerformed

    private void bed_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bed_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bed_codeActionPerformed

    private void diet_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diet_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diet_codeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_patient(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JSpinner agespinner;
    private javax.swing.JTextField allergy;
    private javax.swing.JTextField bed_code;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JComboBox<String> diet_code;
    private javax.swing.JTextArea disease;
    private javax.swing.JButton editpatientbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton orderfoodbutton;
    private javax.swing.JTextField p_code;
    private javax.swing.JTextField p_name;
    private javax.swing.JButton removepatientbutton;
    // End of variables declaration//GEN-END:variables
}
