package oop_project;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bimindu
 */
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class admin_wardclerk extends javax.swing.JFrame {

    /**
     * Creates new form admin_food
     */
    final String password ="";
    final String username="root";
    final String URL = "jdbc:mysql://localhost:3308/hospital";    
    Connection con = null;
    PreparedStatement Insertps = null;
    ResultSet rs =null;
    
    public admin_wardclerk() {
        initComponents();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                con = DriverManager.getConnection(URL,username,password);
            } catch (SQLException ex) {
                Logger.getLogger(admin_wardclerk.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(admin_wardclerk.class.getName()).log(Level.SEVERE, null, ex);
        }
        removewardclerkcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void removewardclerkcombo(){         
    String sql1 = "select ATTCODE from wardclerk";
        try {
            Insertps = con.prepareStatement(sql1);
            rs = Insertps.executeQuery();
            while(rs.next()){
                editatt_code.addItem(rs.getString("ATTCODE"));
                WCremove.addItem(rs.getString("ATTCODE"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin_wardclerk.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        newWCclear = new javax.swing.JButton();
        newWCadd = new javax.swing.JButton();
        newWCpassword = new javax.swing.JTextField();
        newWCusername = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        WCremove = new javax.swing.JComboBox<>();
        wcremovebutton = new javax.swing.JButton();
        editWCclear = new javax.swing.JButton();
        editWCchange = new javax.swing.JButton();
        editWCpassword = new javax.swing.JTextField();
        editatt_code = new javax.swing.JComboBox<>();
        WCname = new javax.swing.JTextField();
        att_code = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 370, 80));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add Ward Clerk");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Att_Code");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("User Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, -1));

        newWCclear.setBackground(new java.awt.Color(255, 0, 0));
        newWCclear.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        newWCclear.setForeground(new java.awt.Color(242, 242, 242));
        newWCclear.setText("Clear");
        newWCclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWCclearActionPerformed(evt);
            }
        });
        getContentPane().add(newWCclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, -1, -1));

        newWCadd.setBackground(new java.awt.Color(0, 204, 0));
        newWCadd.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        newWCadd.setForeground(new java.awt.Color(242, 242, 242));
        newWCadd.setText("Add");
        newWCadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWCaddActionPerformed(evt);
            }
        });
        getContentPane().add(newWCadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, -1, -1));
        getContentPane().add(newWCpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 210, -1));
        getContentPane().add(newWCusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 210, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Edit Ward Clerk");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Att_Code");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Remove Ward Clerk");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 470, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ward Clerk code");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, -1, -1));

        WCremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WCremoveActionPerformed(evt);
            }
        });
        getContentPane().add(WCremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 510, 210, -1));

        wcremovebutton.setBackground(new java.awt.Color(255, 0, 0));
        wcremovebutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        wcremovebutton.setForeground(new java.awt.Color(255, 255, 255));
        wcremovebutton.setText("REMOVE");
        wcremovebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wcremovebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(wcremovebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 540, -1, -1));

        editWCclear.setBackground(new java.awt.Color(255, 0, 0));
        editWCclear.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        editWCclear.setForeground(new java.awt.Color(242, 242, 242));
        editWCclear.setText("Clear");
        editWCclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editWCclearActionPerformed(evt);
            }
        });
        getContentPane().add(editWCclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 240, -1, -1));

        editWCchange.setBackground(new java.awt.Color(0, 204, 0));
        editWCchange.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        editWCchange.setForeground(new java.awt.Color(242, 242, 242));
        editWCchange.setText("Change");
        editWCchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editWCchangeActionPerformed(evt);
            }
        });
        getContentPane().add(editWCchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 240, -1, -1));
        getContentPane().add(editWCpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 200, 210, -1));

        editatt_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editatt_codeActionPerformed(evt);
            }
        });
        getContentPane().add(editatt_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 160, 210, -1));
        getContentPane().add(WCname, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 210, -1));
        getContentPane().add(att_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 210, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ward Clerk");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 370, 80));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/4400828_1_70x70.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Food");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 370, 80));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("Chef");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 370, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/cool-background (1) (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newWCclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWCclearActionPerformed
        // TODO add your handling code here:
        att_code.setText("");
        WCname.setText("");
        newWCusername.setText("");
        newWCpassword.setText("");
    }//GEN-LAST:event_newWCclearActionPerformed

    private void newWCaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWCaddActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do You Want To Add Ward Clerk?","Add Ward Clerk", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {
            String attcode = att_code.getText();
            String name = WCname.getText();
            String user = newWCusername.getText();
            String passcode = newWCpassword.getText();
            try {
                Insertps = con.prepareCall("INSERT USERNAMEPASSWORD VALUES(?,?,?,'Ward Clerk')");
                Insertps.setString(1, attcode);
                Insertps.setString(2, user);
                Insertps.setString(3, passcode);
                int i = Insertps.executeUpdate();
                if(i==1){
                    JOptionPane.showMessageDialog(null, "Success!!");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(admin_wardclerk.class.getName()).log(Level.SEVERE, null, ex);
            }
            String sql = "INSERT wardclerk VALUES('"+attcode+"','"+name+"')";
            try {
                Insertps = con.prepareCall(sql);
                int i = Insertps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(admin_wardclerk.class.getName()).log(Level.SEVERE, null, ex);
            }
            admin_wardclerk aw = new admin_wardclerk();
            aw.setVisible(true);
            dispose();

        }else{

        }
    }//GEN-LAST:event_newWCaddActionPerformed

    private void editWCclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editWCclearActionPerformed
        // TODO add your handling code here:
        editWCpassword.setText("");
    }//GEN-LAST:event_editWCclearActionPerformed

    private void editWCchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editWCchangeActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do You Want To Change details?","Edit Ward Clerk", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {
            String passcode = editWCpassword.getText();
            String wc = editatt_code.getSelectedItem().toString();
            String sql = "UPDATE usernamepassword SET PASSWORD = '"+passcode+"' WHERE EMP_CODE = '"+wc+"'";
            try {
                Insertps = con.prepareCall(sql);
                int e = Insertps.executeUpdate();
                if(e==1){
                    JOptionPane.showMessageDialog(null, "Success!!");
                    admin_wardclerk aw = new admin_wardclerk();
            aw.setVisible(true);
            dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(admin_wardclerk.class.getName()).log(Level.SEVERE, null, ex);
            }
            


        }else{

        }
    }//GEN-LAST:event_editWCchangeActionPerformed

    private void WCremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WCremoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WCremoveActionPerformed

    private void wcremovebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wcremovebuttonActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do You Want To Remove This WardClerk?","Delete Ward Clerk", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {   String apnd = "'"+WCremove.getSelectedItem()+"'";
            String sql = "DELETE FROM wardclerk WHERE ATTCODE = "+apnd ;
            try {
                Insertps = con.prepareStatement(sql);
                int x = Insertps.executeUpdate();

                if(x==1){
                    JOptionPane.showMessageDialog(null, "Ward Clerk removed Successfully!!");
                    
                }
                Insertps = con.prepareCall("DELETE FROM usernamepassword WHERE EMP_CODE = "+apnd);
                int m = Insertps.executeUpdate();
                admin_wardclerk aw = new admin_wardclerk();
            aw.setVisible(true);
            dispose();

            } catch (SQLException ex) {
                Logger.getLogger(admin_wardclerk.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            

        }else{
            JOptionPane.showMessageDialog(null, "Removal Failed!!", "Failed", HEIGHT);
        }
    }//GEN-LAST:event_wcremovebuttonActionPerformed

    private void editatt_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editatt_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editatt_codeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        admin ad = new admin();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        admin_chef ac = new admin_chef();
        ac.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        admin_admin aa = new admin_admin();
        aa.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                admin_wardclerk  aw = new admin_wardclerk();
                aw.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField WCname;
    private javax.swing.JComboBox<String> WCremove;
    private javax.swing.JTextField att_code;
    private javax.swing.JButton editWCchange;
    private javax.swing.JButton editWCclear;
    private javax.swing.JTextField editWCpassword;
    private javax.swing.JComboBox<String> editatt_code;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton newWCadd;
    private javax.swing.JButton newWCclear;
    private javax.swing.JTextField newWCpassword;
    private javax.swing.JTextField newWCusername;
    private javax.swing.JButton wcremovebutton;
    // End of variables declaration//GEN-END:variables
}
