package oop_project;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bimindu
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class admin_chef extends javax.swing.JFrame {

    /**
     * Creates new form admin_food
     */
    final String password ="";
    final String username="root";
    final String URL = "jdbc:mysql://localhost:3308/hospital";    
    Connection con = null;
    PreparedStatement Insertps = null;
    ResultSet rs =null;
    
    public admin_chef() {
        initComponents();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                con = DriverManager.getConnection(URL,username,password);
            } catch (SQLException ex) {
                Logger.getLogger(admin_chef.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(admin_chef.class.getName()).log(Level.SEVERE, null, ex);
        }
        chefcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void chefcombo(){         
    String sql1 = "select CHEFCODE from chef";
        try {
            Insertps = con.prepareStatement(sql1);
            rs = Insertps.executeQuery();
            while(rs.next()){
                editchefcode.addItem(rs.getString("CHEFCODE"));
                removechefcode.addItem(rs.getString("CHEFCODE"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin_chef.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        removechefbutton = new javax.swing.JButton();
        removechefcode = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        editchefchangebutton = new javax.swing.JButton();
        editchefpassword = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        editchefclearbutton = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        editchefcode = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        newchefclearbutton = new javax.swing.JButton();
        newchefaddbutton = new javax.swing.JButton();
        newchefpassword = new javax.swing.JPasswordField();
        newchefusername = new javax.swing.JTextField();
        newchefname = new javax.swing.JTextField();
        newchefcode = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 370, 80));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Chef");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 370, 80));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/4400828_1_70x70.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Ward Clerk");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 370, 80));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Add Chef");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 70, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Chef Code");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        removechefbutton.setBackground(new java.awt.Color(255, 0, 0));
        removechefbutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        removechefbutton.setForeground(new java.awt.Color(255, 255, 255));
        removechefbutton.setText("Romove");
        removechefbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removechefbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(removechefbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 510, -1, -1));

        removechefcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removechefcodeActionPerformed(evt);
            }
        });
        getContentPane().add(removechefcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 480, 220, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Chef Code");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Remove Chef");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 450, 100, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Name");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("User Name");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Edit Chef");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 90, 90, 20));

        editchefchangebutton.setBackground(new java.awt.Color(0, 204, 0));
        editchefchangebutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        editchefchangebutton.setForeground(new java.awt.Color(255, 255, 255));
        editchefchangebutton.setText("Change\n");
        editchefchangebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editchefchangebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(editchefchangebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 210, -1, -1));

        editchefpassword.setAutoscrolls(false);
        getContentPane().add(editchefpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 170, 210, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Password");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 170, -1, -1));

        editchefclearbutton.setBackground(new java.awt.Color(255, 0, 0));
        editchefclearbutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        editchefclearbutton.setForeground(new java.awt.Color(255, 255, 255));
        editchefclearbutton.setText("Clear");
        editchefclearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editchefclearbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(editchefclearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 210, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Chef Code");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 130, -1, -1));

        editchefcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(editchefcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 130, 210, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Password");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, -1, -1));

        newchefclearbutton.setBackground(new java.awt.Color(255, 0, 0));
        newchefclearbutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        newchefclearbutton.setForeground(new java.awt.Color(255, 255, 255));
        newchefclearbutton.setText("Clear");
        newchefclearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newchefclearbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(newchefclearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, -1, -1));

        newchefaddbutton.setBackground(new java.awt.Color(0, 204, 0));
        newchefaddbutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        newchefaddbutton.setForeground(new java.awt.Color(255, 255, 255));
        newchefaddbutton.setText("Add");
        newchefaddbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newchefaddbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(newchefaddbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, -1, -1));
        getContentPane().add(newchefpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 210, -1));
        getContentPane().add(newchefusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 210, -1));
        getContentPane().add(newchefname, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 210, -1));
        getContentPane().add(newchefcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 210, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("Food");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 370, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/cool-background (1) (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void newchefclearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newchefclearbuttonActionPerformed
        // TODO add your handling code here:
        newchefcode.setText("");
        newchefname.setText("");
        newchefusername.setText("");
        newchefpassword.setText("");
    }//GEN-LAST:event_newchefclearbuttonActionPerformed

    private void newchefaddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newchefaddbuttonActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do You Want To Add Chef?","Add Chef", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {   
            String chefcode = newchefcode.getText();
            String name = newchefname.getText();
            String user = newchefusername.getText();
            String passcode = newchefpassword.getText();
            try {
                Insertps = con.prepareCall("INSERT INTO USERNAMEPASSWORD VALUES(?,?,?,'Chef')");
                Insertps.setString(1,chefcode);
                Insertps.setString(2, user);
                Insertps.setString(3, passcode);
                int i = Insertps.executeUpdate();
                if(i==1){
                    JOptionPane.showMessageDialog(null, "Success!!");
                }
                String sql = "INSERT CHEF VALUES('"+chefcode+"','"+name+"')";
            try {
                int n = Insertps.executeUpdate(sql);
                if(n==1){
                    JOptionPane.showMessageDialog(null, "Success!!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(admin_chef.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                new admin_chef().setVisible(true);
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(admin_chef.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{

        }
    }//GEN-LAST:event_newchefaddbuttonActionPerformed

    private void editchefchangebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editchefchangebuttonActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do You Want To Change details?","Edit Chef", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {
            String passcode = editchefpassword.getText();
            String chefcode = editchefcode.getSelectedItem().toString();
            String sql = "UPDATE usernamepassword SET PASSWORD = '"+passcode+"' WHERE EMP_CODE = '"+chefcode+"'";
            try {
                int n = Insertps.executeUpdate(sql);
                if(n==1){
                    JOptionPane.showMessageDialog(null, "Success!!");
                }
                new admin_chef().setVisible(true);
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(admin_chef.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{

        }
    }//GEN-LAST:event_editchefchangebuttonActionPerformed

    private void editchefclearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editchefclearbuttonActionPerformed
        // TODO add your handling code here:
        editchefpassword.setText("");
    }//GEN-LAST:event_editchefclearbuttonActionPerformed

    private void removechefbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removechefbuttonActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do You Want To Remove This Chef?","Delete Chef", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {   String apnd = "'"+removechefcode.getSelectedItem()+"'";
            String sql = "DELETE FROM chef WHERE CHEFCODE = "+apnd ;
            try {
                Insertps = con.prepareStatement(sql);
                int x = Insertps.executeUpdate();

                if(x==1){
                    JOptionPane.showMessageDialog(null, "Ward Clerk removed Successfully!!");
                }
                Insertps = con.prepareCall("DELETE FROM usernamepassword WHERE EMP_CODE = "+apnd);
                int m = Insertps.executeUpdate();

            } catch (SQLException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            new admin_chef().setVisible(true);
                dispose();

        }else{
            JOptionPane.showMessageDialog(null, "Removal Failed!!", "Failed", HEIGHT);
        }
    }//GEN-LAST:event_removechefbuttonActionPerformed

    private void removechefcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removechefcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removechefcodeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        admin ad = new admin();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         admin_wardclerk aw= new admin_wardclerk();
        aw.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        admin_admin aa = new admin_admin();
        aa.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                admin_chef  aw = new admin_chef();
                aw.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editchefchangebutton;
    private javax.swing.JButton editchefclearbutton;
    private javax.swing.JComboBox<String> editchefcode;
    private javax.swing.JTextField editchefpassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton newchefaddbutton;
    private javax.swing.JButton newchefclearbutton;
    private javax.swing.JTextField newchefcode;
    private javax.swing.JTextField newchefname;
    private javax.swing.JPasswordField newchefpassword;
    private javax.swing.JTextField newchefusername;
    private javax.swing.JButton removechefbutton;
    private javax.swing.JComboBox<String> removechefcode;
    // End of variables declaration//GEN-END:variables
}
