/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_project;

/**
 *
 * @author Bimindu
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    final String password ="";
    final String username="root";
    final String URL = "jdbc:mysql://localhost:3308/hospital";    
    Connection con = null;
    PreparedStatement Insertps = null;
    ResultSet rs =null; 
    
    public admin() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                con = DriverManager.getConnection(URL,username,password);
            } catch (SQLException ex) {
                Logger.getLogger(add_patient.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(add_patient.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        foodcombo();
        chefcombo();
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
         
    
    
    
    private void foodcombo(){         
    String sql = "select FOODCODE from food";
        try {
            Insertps = con.prepareStatement(sql);
            rs = Insertps.executeQuery();
            while(rs.next()){
                removefoodcode.addItem(rs.getString("FOODCODE"));
                editfoodcode.addItem(rs.getString("FOODCODE"));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    private void chefcombo(){         
    String sql1 = "select CHEFCODE from chef";
        try {
            Insertps = con.prepareStatement(sql1);
            rs = Insertps.executeQuery();
            while(rs.next()){
                newfoodechefcode.addItem(rs.getString("CHEFCODE"));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin_chef.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        removefoodcode = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        newfoodcode = new javax.swing.JTextField();
        newdietcode = new javax.swing.JTextField();
        newfoodname = new javax.swing.JTextField();
        newfoodaddbutton = new javax.swing.JButton();
        newfoodclearbutton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        editfoodcode = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        editfoodname = new javax.swing.JTextField();
        editfoodclearbutton = new javax.swing.JButton();
        editfoodupdatebutton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        newfoodechefcode = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        backgroundpic = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Welcome, ADMIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 310, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Remove Food");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, -1, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Food Code");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, -1, -1));

        removefoodcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removefoodcodeActionPerformed(evt);
            }
        });
        getContentPane().add(removefoodcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 460, 210, -1));

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(242, 242, 242));
        jButton6.setText("Remove");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 500, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Add Food");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Food Code");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Diet Code");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 60, 10));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Food Name");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));
        getContentPane().add(newfoodcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 210, -1));
        getContentPane().add(newdietcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 210, -1));
        getContentPane().add(newfoodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 210, -1));

        newfoodaddbutton.setBackground(new java.awt.Color(0, 204, 0));
        newfoodaddbutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        newfoodaddbutton.setForeground(new java.awt.Color(255, 255, 255));
        newfoodaddbutton.setText("Add");
        newfoodaddbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newfoodaddbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(newfoodaddbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 290, 100, 30));

        newfoodclearbutton.setBackground(new java.awt.Color(255, 0, 0));
        newfoodclearbutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        newfoodclearbutton.setForeground(new java.awt.Color(242, 242, 242));
        newfoodclearbutton.setText("Clear");
        newfoodclearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newfoodclearbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(newfoodclearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 100, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Edit Food");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("Ward Clerk");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 370, 80));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setText("Chef");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 370, 80));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 370, 80));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Food");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 370, 80));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Food Code");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130, -1, -1));

        getContentPane().add(editfoodcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 130, 220, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Food Name");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 170, -1, -1));
        getContentPane().add(editfoodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, 220, -1));

        editfoodclearbutton.setBackground(new java.awt.Color(255, 0, 0));
        editfoodclearbutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        editfoodclearbutton.setForeground(new java.awt.Color(255, 255, 255));
        editfoodclearbutton.setText("Clear");
        editfoodclearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editfoodclearbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(editfoodclearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 200, 100, 30));

        editfoodupdatebutton.setBackground(new java.awt.Color(0, 204, 0));
        editfoodupdatebutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        editfoodupdatebutton.setForeground(new java.awt.Color(255, 255, 255));
        editfoodupdatebutton.setText("Update");
        editfoodupdatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editfoodupdatebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(editfoodupdatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1162, 200, 100, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Chef Code");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, 20));

        getContentPane().add(newfoodechefcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 210, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/4400828_1_70x70.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 710, -1, -1));

        backgroundpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/cool-background (1) (2).png"))); // NOI18N
        backgroundpic.setText(" ");
        getContentPane().add(backgroundpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do You Want To Remove This Food","Remove Food", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {
            String code = removefoodcode.getSelectedItem().toString();
            
            try {
                String sql1 = "DELETE FROM FOOD WHERE FOODCODE='"+code+"'";
                Insertps = con.prepareCall(sql1);
                int x = Insertps.executeUpdate();
                
                String sql2 = "DELETE FROM FOODCHEF WHERE FOODCODE='"+code+"'";
                Insertps = con.prepareCall(sql2);
                int y = Insertps.executeUpdate();
                
                String sql3 = "DELETE FROM DIETFOOD WHERE FOODCODE='"+code+"'";
                Insertps = con.prepareCall(sql3);
                int z = Insertps.executeUpdate();
                if(x==1 && y==1 && z==1){
                    JOptionPane.showMessageDialog(null, "Success!!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
             
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void removefoodcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removefoodcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removefoodcodeActionPerformed

    private void editfoodupdatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editfoodupdatebuttonActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do You Want To Edit Food?","Edit Food", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {
            String name = editfoodname.getText();
            String code = editfoodcode.getSelectedItem().toString();
            String sql = "UPDATE food set FOODNAME = '"+name+"' WHERE FOODCODE = '"+code+"'";
            try {
                Insertps = con.prepareCall(sql);
                int i = Insertps.executeUpdate();
                if(i==1){
                    JOptionPane.showMessageDialog(null, "Success!!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
             
        }
    }//GEN-LAST:event_editfoodupdatebuttonActionPerformed

    private void newfoodaddbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newfoodaddbuttonActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do You Want To Add Food?","Add Food", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {
            String foodcode = newfoodcode.getText();
            String dietcode = newdietcode.getText();
            String name = newfoodname.getText();
            String chef = newfoodechefcode.getSelectedItem().toString();
        
        
            try {
                String sql = "INSERT INTO FOOD VALUES('"+foodcode+"','"+name+"')";
                Insertps = con.prepareCall(sql);
                int e = Insertps.executeUpdate();
                
                String sql1 = "INSERT INTO DIETFOOD VALUES('"+dietcode+"','"+foodcode+"')";
                Insertps = con.prepareCall(sql1);
                int f = Insertps.executeUpdate();
                
                String sql2 = "INSERT INTO FOODCHEF VALUES('"+foodcode+"','"+chef+"')";
                Insertps = con.prepareCall(sql2);
                int g = Insertps.executeUpdate();
                admin am = new admin();
                am.setVisible(true);
            } catch (SQLException ex) {
//                Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_newfoodaddbuttonActionPerformed

    private void newfoodclearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newfoodclearbuttonActionPerformed
        // TODO add your handling code here:
        newfoodcode.setText("");
        newfoodname.setText("");
        newdietcode.setText("");
        
    }//GEN-LAST:event_newfoodclearbuttonActionPerformed

    private void editfoodclearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editfoodclearbuttonActionPerformed
        // TODO add your handling code here:
        editfoodname.setText("");
    }//GEN-LAST:event_editfoodclearbuttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        admin_wardclerk aw= new admin_wardclerk();
        aw.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        admin_chef ac = new admin_chef();
        ac.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        admin_admin aa = new admin_admin();
        aa.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundpic;
    private javax.swing.JButton editfoodclearbutton;
    private javax.swing.JComboBox<String> editfoodcode;
    private javax.swing.JTextField editfoodname;
    private javax.swing.JButton editfoodupdatebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField newdietcode;
    private javax.swing.JButton newfoodaddbutton;
    private javax.swing.JButton newfoodclearbutton;
    private javax.swing.JTextField newfoodcode;
    private javax.swing.JComboBox<String> newfoodechefcode;
    private javax.swing.JTextField newfoodname;
    private javax.swing.JComboBox<String> removefoodcode;
    // End of variables declaration//GEN-END:variables
}
