package oop_project;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bimindu
 */
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Edit_patient extends javax.swing.JFrame {

    /**
     * Creates new form Remove_patient
     */
    final String password ="";
    final String username="root";
    final String URL = "jdbc:mysql://localhost:3308/hospital";    
    Connection con = null;
    PreparedStatement Insertps = null;
    ResultSet rs =null;
    Statement statement;
    String WC;
    public Edit_patient(String wccode) {
        WC = wccode;
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                con = DriverManager.getConnection(URL,username,password);
            } catch (SQLException ex) {
                Logger.getLogger(add_patient.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(add_patient.class.getName()).log(Level.SEVERE, null, ex);
        }
        patientcodecombo();
        dietcodecombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void patientcodecombo(){         
    String sql = "select PCODE from patient";
        try {
            Insertps = con.prepareStatement(sql);
            rs = Insertps.executeQuery();
            while(rs.next()){
                patientcode.addItem(rs.getString("PCODE"));
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    private void dietcodecombo(){         
    String sql = "select distinct DIETCODE from DIETFOOD";
        try {
            Insertps = con.prepareStatement(sql);
            rs = Insertps.executeQuery();
            while(rs.next()){
                dietcode.addItem(rs.getString("DIETCODE"));
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        removepatientbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patientcode = new javax.swing.JComboBox<>();
        bedcode = new javax.swing.JTextField();
        clearbutton = new javax.swing.JButton();
        enterbutton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        addpatientbutton = new javax.swing.JButton();
        orderfoodbutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        patientname = new javax.swing.JTextField();
        dietcode = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Edit Patient");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 282, 59));

        removepatientbutton.setBackground(new java.awt.Color(205, 102, 0));
        removepatientbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        removepatientbutton.setForeground(new java.awt.Color(255, 255, 255));
        removepatientbutton.setText("Remove Patient");
        removepatientbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removepatientbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(removepatientbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 370, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Patient code");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 90, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Patient Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, -1, -1));

        getContentPane().add(patientcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, 250, -1));
        getContentPane().add(bedcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, 250, -1));

        clearbutton.setBackground(new java.awt.Color(255, 0, 0));
        clearbutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(242, 242, 242));
        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(clearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, 120, 40));

        enterbutton.setBackground(new java.awt.Color(0, 204, 51));
        enterbutton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        enterbutton.setForeground(new java.awt.Color(242, 242, 242));
        enterbutton.setText("Enter");
        enterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(enterbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 320, 120, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Edit Patient");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 370, 80));

        addpatientbutton.setBackground(new java.awt.Color(0, 153, 0));
        addpatientbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addpatientbutton.setForeground(new java.awt.Color(255, 255, 255));
        addpatientbutton.setText("Add Patient");
        addpatientbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpatientbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(addpatientbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 370, 80));

        orderfoodbutton.setBackground(new java.awt.Color(153, 0, 153));
        orderfoodbutton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        orderfoodbutton.setForeground(new java.awt.Color(255, 255, 255));
        orderfoodbutton.setText("Order Food");
        orderfoodbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderfoodbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(orderfoodbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 370, 80));

        logoutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/4400828_1_70x70.png"))); // NOI18N
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 710, -1, -1));
        getContentPane().add(patientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 250, -1));

        getContentPane().add(dietcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, 250, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Diet Code");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Bed Code");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/doctor.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removepatientbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removepatientbuttonActionPerformed
        // TODO add your handling code here:
        Remove_patient rp =new Remove_patient(WC);
        rp.setVisible(true);
        dispose();
    }//GEN-LAST:event_removepatientbuttonActionPerformed

    
    private void addpatientbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpatientbuttonActionPerformed
        // TODO add your handling code here:
        add_patient ap =new add_patient(WC);
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_addpatientbuttonActionPerformed

    private void orderfoodbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderfoodbuttonActionPerformed
        // TODO add your handling code here:
        order_food of = new order_food(WC);
        of.setVisible(true);
        dispose();
    }//GEN-LAST:event_orderfoodbuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        patientname.setText("");
        bedcode.setText("");
        
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void enterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterbuttonActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do You Want To Edit this Patient ?","Edit Patient", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {   
            String pcode = patientcode.getSelectedItem().toString();
            String pname = patientname.getText();
            String Bed = bedcode.getText();
            String diet = dietcode.getSelectedItem().toString();
            if(!pname.isEmpty()){
                String sql = "UPDATE PATIENT SET PNAME = '"+  pname+"' where PCODE = '"+pcode+"'";
                try {
                    Insertps = con.prepareStatement(sql);
                    Insertps.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(Edit_patient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            if(!Bed.isEmpty()){
                String sql = "UPDATE PATIENT SET BEDCODE ='"+Bed+"'where PCODE = '"+pcode+"'";
                try {
                    Insertps = con.prepareStatement(sql);
                    Insertps.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(Edit_patient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(!diet.isEmpty()){
                String sql = "UPDATE PATIENT SET DIETCODE ='"+ diet +"'where PCODE = '"+pcode+"'";
                try {
                    Insertps = con.prepareStatement(sql);
                    Insertps.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(Edit_patient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            JOptionPane.showMessageDialog(null,"Edited Patient Successfully!!");
        }else{
             JOptionPane.showMessageDialog(null, "Error Occured!!");
        }
    }//GEN-LAST:event_enterbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_patient(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpatientbutton;
    private javax.swing.JTextField bedcode;
    private javax.swing.JButton clearbutton;
    private javax.swing.JComboBox<String> dietcode;
    private javax.swing.JButton enterbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton orderfoodbutton;
    private javax.swing.JComboBox<String> patientcode;
    private javax.swing.JTextField patientname;
    private javax.swing.JButton removepatientbutton;
    // End of variables declaration//GEN-END:variables
}
