/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_project;

import javax.swing.JOptionPane;

/**
 *
 * @author Bimindu
 */
public class load extends javax.swing.JFrame {
    static int i = 0;
    /**
     * Creates new form load
     */
    public load() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        loadingvalue = new javax.swing.JLabel();
        function = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(960, 540));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingvalue.setForeground(new java.awt.Color(255, 255, 255));
        loadingvalue.setText("0%");
        jPanel2.add(loadingvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, -1, -1));

        function.setForeground(new java.awt.Color(255, 255, 255));
        function.setText("Loading...");
        jPanel2.add(function, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 140, -1));

        ProgressBar.setForeground(new java.awt.Color(0, 153, 204));
        jPanel2.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 470, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/loading.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        load ld = new load();
        ld.setVisible(true);
        try{
            for(int i=0;i<=100;i++){
                Thread.sleep(10);
                ld.loadingvalue.setText(i+"%");
                if(i==10){
                   ld.function.setText("Turning ON Modules..");
                }
                if(i==20){
                   ld.function.setText("Loading Modules..");
                  
                }
                if(i==50){
                   ld.function.setText("Connecting To Database..");
                }
                if(i==70){
                   ld.function.setText("Connection Successful!!");
                }
                if(i==80){
                   ld.function.setText("Launching Application..");
                }
                ld.ProgressBar.setValue(i);
                
                if(i==100){
                login log = new login();
                log.setVisible(true);
                }
                   
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel function;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loadingvalue;
    // End of variables declaration//GEN-END:variables
}
