/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_project;




import java.awt.List;
import java.awt.Toolkit;

/**
 *
 * @author Bimindu
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    //String[] passes = new String[150]
  
    String WC;
    boolean error = false;
    public login() {
        
        initComponents();
        errormsg.setVisible(false);
        
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionselect = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        resetbutton = new javax.swing.JButton();
        loginbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        userpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        usernameword = new javax.swing.JTextField();
        errormsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(960, 540));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        positionselect.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        positionselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ward Clerk", "Chef", "Admin" }));
        getContentPane().add(positionselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 240, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Log-in");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 170, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Log to the system as ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, 30));

        resetbutton.setBackground(new java.awt.Color(255, 0, 0));
        resetbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resetbutton.setForeground(new java.awt.Color(255, 255, 255));
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(resetbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 110, 50));

        loginbutton.setBackground(new java.awt.Color(0, 204, 0));
        loginbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(242, 242, 242));
        loginbutton.setText("Log-in");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 110, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/login.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 1000, 1080));
        getContentPane().add(userpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 240, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("User Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        usernameword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamewordActionPerformed(evt);
            }
        });
        getContentPane().add(usernameword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 240, 40));

        errormsg.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        errormsg.setForeground(new java.awt.Color(255, 0, 0));
        errormsg.setText("Sorry! Either username or password is wrong!! ");
        getContentPane().add(errormsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 380, 20));

        getAccessibleContext().setAccessibleName("\n");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernamewordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamewordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usernamewordActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed


        // TODO add your handling code here:
        try {
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/hospital", "root", "");
        
        String s = "select USERNAME,PASSWORD,POSITION,EMP_CODE from usernamepassword where USERNAME=? and PASSWORD=? and POSITION=?";
        if ((positionselect.getSelectedItem().toString())=="Ward Clerk"){
        PreparedStatement ps = con.prepareStatement(s);
        ps.setString(1, usernameword.getText());
        ps.setString(2, userpassword.getText());
        ps.setString(3, positionselect.getSelectedItem().toString());
        
        ResultSet rs = ps.executeQuery();
        
             if(rs.next()){
                 WC = rs.getString("EMP_CODE");
                 new order_food(WC).setVisible(true);
                 
             }
             else 
                 
                  JOptionPane.showMessageDialog(this,"Login Failed");
                 errormsg.setVisible(true);
        }
        
        else if ((positionselect.getSelectedItem().toString())=="Chef"){
        PreparedStatement ps = con.prepareStatement(s);
        ps.setString(1, usernameword.getText());
        ps.setString(2, userpassword.getText());
        ps.setString(3, positionselect.getSelectedItem().toString());
        
        ResultSet rs = ps.executeQuery();
        
             if(rs.next()){
                 
                 new chef1().setVisible(true);
                 
             }
             else 
                 
                  JOptionPane.showMessageDialog(this,"Login Failed");
            errormsg.setVisible(true);
        }
        
        else if ((positionselect.getSelectedItem().toString())=="Admin"){
        PreparedStatement ps = con.prepareStatement(s);
        ps.setString(1, usernameword.getText());
        ps.setString(2, userpassword.getText());
        ps.setString(3, positionselect.getSelectedItem().toString());
        
        ResultSet rs = ps.executeQuery();
        
             if(rs.next()){
                 
                 new admin().setVisible(true);
                 
             }
             else 
                 
                  JOptionPane.showMessageDialog(this,"Login Failed");
            errormsg.setVisible(true);
        }
             
        
        }catch(Exception e){
        
            System.out.println(e);
        
        }
       

    }//GEN-LAST:event_loginbuttonActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        // TODO add your handling code here:
        usernameword.setText("");
        userpassword.setText("");
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                login log = new login();
                log.setVisible(true);
                //log.setExtendedState(jFrame.MAXIMIZED_BOTH); 
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel errormsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginbutton;
    private javax.swing.JComboBox<String> positionselect;
    private javax.swing.JButton resetbutton;
    public javax.swing.JTextField usernameword;
    private javax.swing.JPasswordField userpassword;
    // End of variables declaration//GEN-END:variables
}
