/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_project;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Bimindu
 */
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime; 
import static javax.swing.Action.DEFAULT;
public class order_food extends javax.swing.JFrame  {
    
    
    final String password ="";
    final String username="root";
    final String URL = "jdbc:mysql://localhost:3308/hospital";    
    Connection con = null;
    PreparedStatement Insertps = null;
    ResultSet rs =null;
    Statement statement;
    String dietcode;
    /**
     * Creates new form order_food
     */
    String WC ;
    public order_food(String wccode) {
        WC = wccode;
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                con = DriverManager.getConnection(URL,username,password);
            } catch (SQLException ex) {
                Logger.getLogger(add_patient.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(add_patient.class.getName()).log(Level.SEVERE, null, ex);
        }
        patientcodecombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void patientcodecombo(){         
    String sql = "select PCODE from patient";
        try {
            Insertps = con.prepareStatement(sql);
            rs = Insertps.executeQuery();
            while(rs.next()){
                patientcode.addItem(rs.getString("PCODE"));
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patientcode = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        removepatient = new javax.swing.JButton();
        addpatint = new javax.swing.JButton();
        editpatient = new javax.swing.JButton();
        foodname = new javax.swing.JComboBox<>();
        logout = new javax.swing.JButton();
        orderbutton = new javax.swing.JButton();
        searchfood = new javax.swing.JButton();
        bedcode = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        foodcode = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Order food");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, 197, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Bed code");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 70, -1));

        patientcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        patientcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientcodeActionPerformed(evt);
            }
        });
        getContentPane().add(patientcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 150, 270, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Patient Code");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, -1, -1));

        removepatient.setBackground(new java.awt.Color(204, 102, 0));
        removepatient.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        removepatient.setForeground(new java.awt.Color(255, 255, 255));
        removepatient.setText("Remove Patient");
        removepatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removepatientActionPerformed(evt);
            }
        });
        getContentPane().add(removepatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 370, 80));

        addpatint.setBackground(new java.awt.Color(0, 153, 0));
        addpatint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addpatint.setForeground(new java.awt.Color(255, 255, 255));
        addpatint.setText("Add Patient");
        addpatint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpatintActionPerformed(evt);
            }
        });
        getContentPane().add(addpatint, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 370, 80));

        editpatient.setBackground(new java.awt.Color(204, 0, 0));
        editpatient.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        editpatient.setForeground(new java.awt.Color(255, 255, 255));
        editpatient.setText("Edit Patient");
        editpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editpatientActionPerformed(evt);
            }
        });
        getContentPane().add(editpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 370, 80));

        foodname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodnameActionPerformed(evt);
            }
        });
        getContentPane().add(foodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 280, 270, 30));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/4400828_1_70x70.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 710, -1, -1));

        orderbutton.setBackground(new java.awt.Color(255, 0, 0));
        orderbutton.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        orderbutton.setForeground(new java.awt.Color(242, 242, 242));
        orderbutton.setText("Order");
        orderbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(orderbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 380, 270, 40));

        searchfood.setBackground(new java.awt.Color(0, 204, 51));
        searchfood.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        searchfood.setForeground(new java.awt.Color(255, 255, 255));
        searchfood.setText("Search Food");
        searchfood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfoodActionPerformed(evt);
            }
        });
        getContentPane().add(searchfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, 270, 30));

        bedcode.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bedcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(bedcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 270, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("Food Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 90, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Order Food");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 370, 80));
        getContentPane().add(foodcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 270, 20));
        foodcode.setVisible(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project images/doctor.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addpatintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpatintActionPerformed
        // TODO add your handling code here:
        add_patient ap = new add_patient(WC);
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_addpatintActionPerformed

    private void orderbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderbuttonActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null,"Do You Want To Order This Food!!","Order", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {
            String pcode = patientcode.getSelectedItem().toString();
            String bed = bedcode.getText();
            String food = foodname.getSelectedItem().toString();
            String sql = "SELECT FOODCODE FROM FOOD WHERE FOODNAME = '"+food+"'";
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
            LocalDateTime now = LocalDateTime.now();  
            System.out.println(dtf.format(now));
            try {
                Insertps = con.prepareStatement(sql);
                rs = Insertps.executeQuery();
                while(rs.next()){
                    foodcode.setText(rs.getString("FOODCODE"));
               
            }
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(order_food.class.getName()).log(Level.SEVERE, null, ex);
            }
            String f_code = foodcode.getText();
            try{
                
                
                int i;
                    String sql1 = "INSERT INTO orders values('"+pcode+"','"+f_code+"','"+food+"', now(),'"+WC+"',DEFAULT)";
                    Insertps = con.prepareStatement(sql1);
                    i=Insertps.executeUpdate();
                        if(i==1){
                            JOptionPane.showMessageDialog(null, "Ordered Successfully", "Success", HEIGHT, new javax.swing.ImageIcon(getClass().getResource("/project images/green-check.png")));
                            
                    try {
                        FileWriter write_file = new FileWriter("details.txt",true);
                        write_file.write(pcode+"\t"+f_code+"\t"+food+"\t"+WC+"\t"+dtf.format(now)+"\n");
                        write_file.close();
                    } catch (IOException ex) {
                        Logger.getLogger(order_food.class.getName()).log(Level.SEVERE, null, ex);
                    }
                            
                        }
            }
             catch (SQLException ex) {
                Logger.getLogger(order_food.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
            
        }else{
             
        }

    }//GEN-LAST:event_orderbuttonActionPerformed

    private void editpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editpatientActionPerformed
        // TODO add your handling code here:
        Edit_patient ep = new Edit_patient(WC);
        ep.setVisible(true);
        dispose();
    }//GEN-LAST:event_editpatientActionPerformed

    private void removepatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removepatientActionPerformed
        // TODO add your handling code here:
        Remove_patient rp = new Remove_patient(WC);
        rp.setVisible(true);
        dispose();
    }//GEN-LAST:event_removepatientActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void patientcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientcodeActionPerformed
        // TODO add your handling code here:
        try {
            String code = patientcode.getSelectedItem().toString();
            String sql3 = "SELECT * FROM PATIENT WHERE PCODE = '"+code+"'";
            Insertps = con.prepareStatement(sql3);
            rs = Insertps.executeQuery();
            while(rs.next()){
                String bed = rs.getString("BEDCODE");
                bedcode.setText(bed);
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_patientcodeActionPerformed

    private void foodnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodnameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_foodnameActionPerformed

    private void searchfoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfoodActionPerformed
        // TODO add your handling code here:
        foodname.removeAllItems();
        String pcode = patientcode.getSelectedItem().toString();
        String sql2 = "SELECT F.FOODNAME FROM PATIENT P INNER JOIN DIETFOOD D ON P.DIETCODE = D.DIETCODE INNER JOIN FOOD F ON D.FOODCODE = F.FOODCODE and P.PCODE = '"+pcode+"'";

        
         try {
           Insertps = con.prepareStatement(sql2);
            rs = Insertps.executeQuery();
            while(rs.next()){
                foodname.addItem(rs.getString("FOODNAME"));
                
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Remove_patient.class.getName()).log(Level.SEVERE, null, ex);
        }
         
            
       
        
        
        
    }//GEN-LAST:event_searchfoodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order_food(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpatint;
    private javax.swing.JLabel bedcode;
    private javax.swing.JButton editpatient;
    private javax.swing.JLabel foodcode;
    private javax.swing.JComboBox<String> foodname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton logout;
    private javax.swing.JButton orderbutton;
    private javax.swing.JComboBox<String> patientcode;
    private javax.swing.JButton removepatient;
    private javax.swing.JButton searchfood;
    // End of variables declaration//GEN-END:variables
}
